version: '3.1'

services:
  vacation-pay-service:
    build: .
    image: min-from-excel-service
    container_name: min-from-excel-service
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro